---
apiVersion: v1
kind: Service
metadata:
  name: nginx-custom-service
  namespace: homework9
  labels:
    app: nginx-custom
spec:
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 9113
  selector:
    app: nginx-custom