---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-homework18-consul-consul-server-0
  namespace: homework18
  annotations:
    volume.beta.kubernetes.io/storage-class: "local-path"
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-homework18-consul-consul-server-1
  namespace: homework18
  annotations:
    volume.beta.kubernetes.io/storage-class: "local-path"
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-homework18-consul-consul-server-2
  namespace: homework18
  annotations:
    volume.beta.kubernetes.io/storage-class: "local-path"
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  storageClassName: local-path