---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "hipster-shop"
  namespace: hipster-shop
  labels:
    app: frontend
  annotations:
    cert-manager.io/cluster-issuer: intermediate-ca-issuer
    cert-manager.io/duration: 8766h
    cert-manager.io/renew-before: 336h
spec:
  ingressClassName: nginx
  tls:
  - secretName: {{ .Values.ingress.secretName }}
    hosts:
    - hipster-shop.company.local
  rules:
    - host: hipster-shop.company.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.service.port }}

